version: "3"
services:
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"

  consul-agent-1: &consul-agent
    image: consul:1.8
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    volumes:
      - './docker-infrastructure/consul.d:/consul/config'
  consul-agent-2:
    <<: *consul-agent
  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
  consul-server-2:
    <<: *consul-server
  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
